name: my_cash_book
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get_storage: ^2.1.1
  get: 4.6.6
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  fl_chart: ^0.63.0
  intl: ^0.18.1
  sqflite: ^2.0.0
  crypto: ^3.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
